### ISSUE TITLE
[Android] The SplashScreen is displaying strangely when it is running 

### ISSUE THREAD

**Issue by Darsh0307** [unoplatform/uno.resizetizer#103]
## Current behavior

When running the android platform for the TubePlayer project the splashscreen should be shown only once but wiredly it is showing us the SplashScreen twice. You can refer to below photo for more details.
<img width="900" alt="Screenshot 2023-03-24 at 5 20 44 AM" src="https://user-images.githubusercontent.com/90713481/227390699-a1c6f003-c9a2-4755-8502-6f1265695da0.png">

## Expected behavior

The middle logo when running the android platform should be only one but it is two. 

## How to reproduce it (as minimally and precisely as possible)

```
		<UnoSplashScreen
			 Include="$(MSBuildThisFileDirectory)SplashScreen\splashscreen.svg"
			 BaseSize="110,110"
			 Color="#FFFFFF" />
```

## Environment

Nuget Package: uno.resizetizer

Package Version(s):  1.0.2

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [x]  2022 (version: Version 17.5.2)
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by pictos** [comment]
@Darsh0307 this isn't a bug, it's a feature :D 

It's caused by this [line](https://github.com/unoplatform/uno.samples-private/blob/feature/youtubeplayer/reference/TubePlayer/TubePlayer.Mobile/Android/Resources/values/Styles.xml#L15-L16), if you don't want the image at the bottom just remove it.

**Comment by jeromelaban** [comment]
@pictos Could we explain that in the documentation? Thanks!

**Comment by pictos** [comment]
@jeromelaban I can, but that's an android specific thing, do you think that makes sense to add on resizetizer's docs?

**Comment by jeromelaban** [comment]
@pictos Yes, it's a behavior that people will likely not understand immediately, it's better to redirect to proper docs in a troubleshooting section.

**Comment by pictos** [comment]
I added it on the docs issue and will work on that ASAP
