### ISSUE TITLE
[Documentation] Feedback for using-uno-resizetizer.md

### ISSUE THREAD

**Issue by agneszitte** [unoplatform/uno.resizetizer#105]
## On which page?
https://github.com/unoplatform/uno.resizetizer/blob/main/doc/using-uno-resizetizer.md

## What's wrong?

- [x] **1. Installing Uno.Resizetizer**
Should be mentioned as an optional step (instead of step 1) for anyone that does not start with the solution template that includes Uno.Resizetizer by default with Uno Platform 4.8.
- [x] **[!TIP] To create an app, make sure to visit our getting started tutorials.**
Add a link in the tip to the getstarted.md
- [x] **Missing screenshots**
Please add proper screenshots of actual svg files in the correct location on all the steps
- [x] **Now open the base.props file, inside the MyApp.Base folder project and add the following block:**
Add a link to the proper file of the sample app as an example will help
- [x] **In each of your project heads (iOS, Android, WebAssembly, ...) add the following block:**
Should precise csproj to make it clear (for UnoIcon and UnoSplashScreen)
- [x] **Adjustments for every platforms**
Please add a link to every file in the sample app matching the adjustments for every platform so it's easier to have a proper example
- [x] **Windows - remove everything that's related to the application icon**
 ![image](https://user-images.githubusercontent.com/16295702/227399123-326fc9a0-a26a-4a41-87e5-f7d298e44831.png)
 We don't show a proper example of anything related to the application that should be removed in this snippet. A proper example of what should be removed should be added instead + a link to the proper matching file in the sample app as an example
 - [x] **#FFFFFF(transparent)**
![image](https://user-images.githubusercontent.com/16295702/227399639-24df701d-65d7-4228-87e9-56396cd71ea7.png)
#FFFFFF is white not transparent
- [ ] **Create a `SplashScreen` folder inside the Base project**
Make sure to update the name of the folder in the Sample App to `SplashScreen` instead of ``Splash` to match
- [x] **Open the Style.xml file**
It should be Styles.xml instead of Style.xml
- [x] **UnoImage - One or more invalid file names were detected. File names must be lowercase, start and end with a letter character, and contain only alphanumeric characters or underscores**
These detail should be mentioned in the documentation also
- [ ] **UnoImage - Image Width="300" Height="300" Source="Assets\Images\myImage.png"**
The source path is incorrect here should be <Image Width="300" Height="300" Source="ms-appx:///NameOfTheApp/Assets/Images/nameoftheasset.png"

**Comment by pictos** [comment]
Add a troubleshot section and add this info
- https://github.com/unoplatform/uno.resizetizer/issues/103?notification_referrer_id=NT_kwDOATwLtLM1OTU0ODk5MjIyOjIwNzEyMzcy&notifications_query=reason%3Aparticipating#issuecomment-1485002278

**Comment by agneszitte-nventive** [comment]
@pictos FYI I added another point to the list after seeing some feedback for another project
Related : `UnoImage - Image Width="300" Height="300" Source="Assets\Images\myImage.png"`
`The source path is incorrect here, should be`
`<Image Width="300" Height="300" Source="ms-appx:///NameOfTheApp/Assets/Images/nameoftheasset.png"`

@jeromelaban I would like to have your feedback on the fact that right now Uno.Resizetizer is forcing lowercase for the svg file name and png name in the path. I asked @pictos to specify this info inside the documentation for the moment, but wondering if we cannot just do something about this directly in Resizetizer instead of forcing the lowercase?
Related: `UnoImage - One or more invalid file names were detected. File names must be lowercase, start and end with a letter character, and contain only alphanumeric characters or underscores`
`These details should be mentioned in the documentation also`

**Comment by jeromelaban** [comment]
We should never be using `\` in image paths. Short-hand paths are just short hand to full URIs, let's not confuse users with a different convention.

**Comment by jeromelaban** [comment]
@pictos for the assets path, the uno assets tooling handles casing properly (there's a generator for that specifically). We should be able to remove that restriction for `UnoImage` at least. Other types like app icon and splashscreen will need to stay lowercased.

**Comment by agneszitte-nventive** [comment]
> @pictos for the assets path, the uno assets tooling handles casing properly (there's a generator for that specifically). We should be able to remove that restriction for `UnoImage` at least. Other types like app icon and splashscreen will need to stay lowercased.

I agree @jeromelaban , that way we can have the proper error message only for icon/splashscreen.
@pictos you can adjust the doc to have the info for the icon/splascreen section only when this will be adjusted in Resizetizer

**Comment by pictos** [comment]
I would say that's a bad approach, having different rules for different build actions. Right now is just one, but it opens precedence for other changes like that in the future. IMHO is better/easier to educate devs right now that in order to use Resizetizer, they should provide lowercase names separated by `_`, instead of creating different rules for different build actions inside the same tool.

**Comment by agneszitte-nventive** [comment]
> I would say that's a bad approach, having different rules for different build actions. Right now is just one, but it opens precedence for other changes like that in the future. IMHO is better/easier to educate devs right now that in order to use Resizetizer, they should provide lowercase names separated by `_`, instead of creating different rules for different build actions inside the same tool.

@pictos but in my opinion, devs were already used to having different rules for app icons and splashscreen on all the different platforms. Now it is simpler while using Resizetizer, it just needs to be properly documented and keep the error message when needed. 
We are used to having upper/lower case for the Images inside the app, so it will be easier for a project already in place to start using Resizetizer as for UnoImages, the only change needed will be in the solution explorer to replace the png with an svg without changing the XAML at all (as the path will be the same and the name of the asset also). 
(cc @jeromelaban)

**Comment by igiona** [comment]
My 2 cents on the file name casing:
as a dev I don't mind having to make the file names dash-separated and lower-case, the error tells you pretty well what you have to do.
Make an aka-URL with the explanation of the rational behind the rule would a good addon, my first thought was "why on earth in 2023 the case of a file becomes a problem?". Knowing the reason can help to accept the limitation 😄

**Comment by igiona** [comment]
Since the Resizetizer works only with vector images (only svg?), I would add an error when the UnoImage ItemGroup 
e.g. <UnoImage Include="Assets\**\*" /> matches non-SVG files.

Or there is another benefit in having UnoImage as DeployAction for (e.g.) PNGs ?

**Comment by pictos** [comment]
@igiona Sorry for the late reply, it's very rush here hehe.

So you can use png files as well, they will be processed but will not be resized.

**Comment by pictos** [comment]
@MartinZikmund if I can remember we'll that restriction will be there, because of Android and here we try to handle the minimum common operator. And this limitation shouldn't be a blocker for any dev using Uno

**Comment by MartinZikmund** [comment]
@pictos but normal jpgs do not have this limitation even in case of Android 🤔, I would expect that because Resizetizer produces scaled pngs, it should ultimately be "equivalent" to just including scaled pngs directly, or am I missing something 👀?
