### ISSUE TITLE
[Android] Unable to deploy after rebuild

### ISSUE THREAD

**Issue by nickrandolph** [unoplatform/uno.resizetizer#106]
## Current behavior

Forcing a rebuild on Mobile project prevents Android app from being able to be deployed with following errors:
12:59:43:995	APT2260: resource drawable/splash_screen (aka com.companyname.UnoApp1:drawable/splash_screen) not found.
12:59:43:996	APT2260: resource drawable/splash_screen (aka com.companyname.UnoApp1:drawable/splash_screen) not found.
12:59:43:996	APT2260: resource drawable/splash_screen (aka com.companyname.UnoApp1:drawable/splash_screen) not found.
12:59:43:996	APT2260: resource drawable/splash_screen (aka com.companyname.UnoApp1:drawable/splash_screen) not found.
12:59:43:996	APT2062: failed linking references.

## Expected behavior

No errors and successful deploy/run

## How to reproduce it (as minimally and precisely as possible)

- Create new project using Blank preset in Wizard
- Build and run the Mobile project
- Force Rebuild on the Mobile project
- Press Run which should deploy and run the project but will fail with errors

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
This may be an uno issue. If you can create a binlog of the issue reproducing, we may be able to find a fix.

**Comment by pictos** [comment]
@jeromelaban I recorded all the binlogs for the steps mentioned by Nick. Let me know if it's something here or on Uno.

[1_FirstBuild.zip](https://github.com/unoplatform/uno.resizetizer/files/11063014/1_FirstBuild.zip)
[2_Rebuild.zip](https://github.com/unoplatform/uno.resizetizer/files/11063015/2_Rebuild.zip)
[3_DeployAndFail.zip](https://github.com/unoplatform/uno.resizetizer/files/11063016/3_DeployAndFail.zip)

**Comment by al-kau** [comment]
Uno Platfrom version 4.8 (Uno template extension: version 4.8.8.8)

I have the same problem. 
file: **UnoApp\UnoApp.Mobile\Android\Resources\values\Styles.xml** has 'splash screen' property.
In my project it looks like this:
```
		<!-- This property is used for the splash screen -->
		<item name="android:windowSplashScreenBackground">#FFFFFF</item>
		<item name="android:windowBackground">@drawable/splash_screen</item>
		<item name="android:windowSplashScreenAnimatedIcon">@drawable/splash_screen</item>
		<!--<item name="android:windowSplashScreenBehavior">1</item>-->
```
The Uno template creates a **UnoApp\UnoApp.Base\Splash\splash_screen.svg** file that is not added to the solution. So splash screens are not generated. And Android app can't find resources.

You can disable 'splash screen' property at **Styles.xml** or try adding images (look at [splash screen docs](https://platform.uno/docs/articles/splash-screen.html?tabs=tabid-vswin#step-3---android))

p.s.
Please, fix the Uno template.

**Comment by Youssef1313** [comment]
Maybe related to? https://github.com/xamarin/xamarin-android/issues/6534
But we should find a workaround anyway.

**Comment by Youssef1313** [comment]
@pictos Would you be able to test if `<CallTarget Targets="_GenerateAndroidResourceDir" />` would workaround this issue? We would force `_GenerateAndroidResourceDir` after resizetizer does its work by adding the CallTarget just before this line:

https://github.com/unoplatform/uno.resizetizer/blob/a394b82c2eeae8e3b8ca858b5d5aa979d32c718d/src/.nuspec/Uno.Resizetizer.targets#L587

**Comment by pictos** [comment]
@Youssef1313 I'll give it a try and post the results here ASAP

**Comment by Youssef1313** [comment]
https://github.com/xamarin/xamarin-android/pull/7780 have fixed a similar error.

I tried to include what is in that PR like this:

```xml
	<Target Name="WorkaroundXamarin7780" Condition="'$(_ResizetizerIsAndroidApp)' == 'True'" AfterTargets="_ResolveLibraryProjectImports">
		<ItemGroup>
			<FileWrites Include="$(_AndroidLibraryProjectImportsCache)"
				Condition="Exists ('$(_AndroidLibraryProjectImportsCache)')"/>
		</ItemGroup>
	</Target>
```

but it didn't work.

I'm out of ideas.
