### ISSUE TITLE
[Dicussion] handling with app icon assets with Resizetizer

### ISSUE THREAD

**Issue by pictos** [unoplatform/uno.resizetizer#109]
# Some title

It's known that each Platform has its own guidelines for handling app icons. In general, Resizetizer can generate assets for both Idioms (mobile and desktop), but it lacks some intrinsic guidelines, where we can't infer if the user will deliver an asset following the guidelines or not. To better illustrate the scenario will be used Android and Windows.

## SVG with padding

The svg used by this first sample is one that respects the guidelines for mobile Idiom. That means the foreground is centered and there's padding, represented by the fact the svg image is smaller than the `ViewBox`. The assets used are in the zip file below.

[icons_with_padding.zip](https://github.com/unoplatform/uno.resizetizer/files/11125263/icons_with_padding.zip)

The dimensions of the Foreground assets are:
`svg width="456" height="456"`
`viewBox="0 0 912 912"`

The dimensions of the Background assets are:
`svg width="456" height="456"`
`viewBox="0 0 456 456"`

As you can see, we just have to add the padding on the Foreground file.

On mobile we will have the following result:

![appIcon_android](https://user-images.githubusercontent.com/20712372/229211173-d8b8c0e6-4f45-459f-8684-6a0c8e1f5fec.png)

As you can see the `Uno logo` is centered and there's a padding around it.

For Windows the result is different, because of that extra size on ViewBox the `Uno logo` becomes very smaller, you can see the result at image below:

![appIcon_windows](https://user-images.githubusercontent.com/20712372/229211212-931a7fc0-2396-441a-8627-ad63080d99bb.png)

## SVG without padding

The svg used by this second sample is one that doesn't respect the guidelines for mobile Idiom. That means the foreground is not centered and there's no padding. The assets used are in the zip file below.

[icons_without_padding.zip](https://github.com/unoplatform/uno.resizetizer/files/11125268/icons_without_padding.zip)

The dimensions of the Foreground assets are:
`svg width="450" height="450"`
`viewBox="0 0 50.369617 49.826836"`

The dimensions of the Background assets are:
`svg width="456" height="456"`
`viewBox="0 0 456 456"`

On mobile we will have the following result:

![old_appIcon_android](https://user-images.githubusercontent.com/20712372/229211285-2c4073de-3db0-4957-8f48-ca9f455a0d8d.png)

As you can see the `Uno logo` fills all the icon space horizontally and vertically. The padding is not respected.

Otherwise, for Windows the result is different, it looks good because the `Uno logo` is centered and the icon is bigger than before. You can see the result in image below:

![old_appIcon_windows](https://user-images.githubusercontent.com/20712372/229211306-602756a6-e03b-43ac-abb0-11d988cfae8a.png)

### 1. Using the ForegroundScale property

If needed the user can specify the scale of the Foreground asset, increasing or reducing its size. Something like this:

```xml
<UnoIcon Include="$(MSBuildThisFileDirectory)Icons\iconapp.svg"
        ForegroundFile="$(MSBuildThisFileDirectory)Icons\appconfig.svg"
        Color="#00000000" 
        ForegroundScale="0.65"/>
```

This can work for some cases, but there are cases where the Foreground just disappears, and it has to do with the content position inside the svg file, I couldn't find a good metric for that with the `svg` that I've available, so that will be a more empiric way to test and resize the app icon.

### 2. During the resizing process, we add a padding to the image

We can infer that assets will not have the padding, so we can add it during the resizing process. And we can do that per platform, which will give us more control over asset generation. The question here is, should this padding be added implicitly or should we add a new property to the `UnoIcon` item? Something like `AddPadding="true"`, where the padding will be implicitly added by Resizetizer defaults, or per platform, something like, `WindowsPadding= "10"` and `AndroidPadding="20"` where the user can specify the padding value for each platform if doesn't specify the value will be `0`.

### 3. Infer that the asset will have a padding

We can infer that the asset will have a padding, so on Desktop idioms we can increase the scale of the generated `ForegroundFile`, that way the icon will not too small.

### 4. Use the platform idioms to take care

Instead of trying to apply those paddings on Resizetizer code (which uses Skia to renderer the image) we can use what the platform gives to us, on android, we can adjust the `inset` property and that will be aligned with their units. So the xml for the adaptive-icon will be:

```xml
<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
  <background android:drawable="@color/ic_launcher_background"/>
  <foreground>
    <inset
      android:drawable="@drawable/ic_launcher_foreground"
      android:inset="16%" />
  </foreground>
</adaptive-icon>
```

For more context and other points of view, you can see this issue on .NET MAUI repo: https://github.com/dotnet/maui/issues/11295
And this one on Flutter's repo: https://github.com/fluttercommunity/flutter_launcher_icons/issues/96

**Comment by pictos** [comment]
Without padding:

svg file:
[Uno_Logo_default.zip](https://github.com/unoplatform/uno.resizetizer/files/11165173/Uno_Logo_default.zip)

result:
![image](https://user-images.githubusercontent.com/20712372/230241551-76772c32-0173-40f6-ad49-6d751cb50f9c.png)



With padding:
svg file:
[Uno_Logo_with_padding.zip](https://github.com/unoplatform/uno.resizetizer/files/11165155/Uno_Logo_with_padding.zip)

result:
![image](https://user-images.githubusercontent.com/20712372/230240807-8703accd-4b6a-4ae6-ae61-9ca1535a16bb.png)


cc: @nickrandolph

**Comment by Darsh0307** [comment]
Hello @nickrandolph  @pictos 
For the tube player project the icon on Android even after using AndroidForegroundScale and properly setting the scale. 
We are not able to get the icon coming in the center, If we see it carefully it is a little bit on the left side. I am also attaching the photo for your response. 
<img width="258" alt="Screenshot 2023-04-24 at 6 40 39 PM" src="https://user-images.githubusercontent.com/90713481/234013718-0292439c-a0e0-42af-a425-b6fddfdaf0dd.png">

**Comment by pictos** [comment]
@Darsh0307, from my last interactions, this is a thing on the `.svg` asset, if you open it on an _svg editor_ you will see it's not centered. So in that case it isn't a Resizetizer issue.

**Comment by agneszitte** [comment]
@pictos I checked the svg files and seems to me the icon is correctly centered
Here are the files if you want to test it on your side:
[TubePlayer app icon svg.zip](https://github.com/unoplatform/uno.resizetizer/files/11311368/TubePlayer.app.icon.svg.zip)

**Comment by pictos** [comment]
@agneszitte I'll take a look asap, will see if I've the asset that I made it work before

**Comment by pictos** [comment]
@Darsh0307 with version of Resizetizer are you using?
