### ISSUE TITLE
[WASM] Splash image disappears on subsequent runs

### ISSUE THREAD

**Issue by nickrandolph** [unoplatform/uno.resizetizer#110]
## Current behavior

Create new app using Blank preset in Wizard
Build and run WASM - correct splash screen image appears (just Uno logo)
Stop, then build and run again
- At some point the correct image isn't displayed and the default splash image is displayed (Uno log with "Uno platform" text)

## Expected behavior

Correct splash should always be displayed

## Repro steps

Create new app using dotnet new
dotnet new unoapp -preset blank -o CheckSplashApp

Open app in Visual Studio
Wait for "reload" message to appear (it may not, so can ignore this step if it doesn't) and click reload
Set Wasm target as start project
**Rebuild** wasm target
Run wasm target without debugging -> this will launch app with correct splash screen
Close browser
Rebuild the class library **not** the wasm project
Run wasm target without debugging -> this will launch app with the wrong splash screen

**Comment by nickrandolph** [comment]
Of course, now that I've logged the issue I can't seem to replicate it - I came across this whilst I was investigating issues raised by @MartinZikmund  on the templates (eg https://github.com/unoplatform/uno.templates/issues/60). In this case you can see that the image includes the "Uno platform" words, which isn't in the splash image (it comes from a hard coded image that's provide by the platform as a fallback)

**Comment by pictos** [comment]
@nickrandolph I tried on my end, with the latest template and couldn't reproduce this issue. When you tested did you have the latest bits?
