### ISSUE TITLE
Link isn't supported for UnoIcon and UnoSplashcreen but it's allowed

### ISSUE THREAD

**Issue by pictos** [unoplatform/uno.resizetizer#119]
Today we support the `Link` metadata on `UnoImage`, the user can set it and use it on your app.

For `UnoIcon` and `UnoSplashScreen` the user can set it, but the build will fail. We should prevent in code the usage of `Link` on those items and show a warning

**Comment by nickrandolph** [comment]
Incremental improvement to support https://github.com/unoplatform/uno.resizetizer/issues/98

**Comment by pictos** [comment]
Closing this one and all the discussion should happen on #98
