### ISSUE TITLE
Icon not set on WinUI window

### ISSUE THREAD

**Issue by nickrandolph** [unoplatform/uno.resizetizer#129]
The .ico file is being created for WinUI but isn't being set on the ApplicationIcon property, so results in the default icon

**Comment by pictos** [comment]
I tried to add the `ico` file directly to the project, so the Resizetizer will not handle that... And the icon didn't show on window. So I'm wondering if there's one more step, on winUI itself, to make that `ico` visible.

```xml
<PropertyGroup>
		<ApplicationIcon>iconapp.ico</ApplicationIcon>
</PropertyGroup>
```

[here's](https://github.com/unoplatform/uno.resizetizer/tree/pj/winui-app-ico) the branch with the change
