### ISSUE TITLE
CS1591 on generated class.

### ISSUE THREAD

**Issue by ADD-David-Antolin** [unoplatform/uno.resizetizer#149]
## Current behavior

A CS1591 compilation error is produced in generated class WindowExtensions when that rule is set to error level. 

## Expected behavior

The class should be documented so it complies with CS1591.

## How to reproduce it (as minimally and precisely as possible)

Create a new Uno project from the VS extension and set the CS1591 to error. Compile Windows project.

## Environment

Nuget Package: Uno.Resizetizer

Package Version(s): 1.1.0

Affected platform(s):

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [X] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2022 (version: 17.6.2)
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

https://github.com/unoplatform/uno.resizetizer/blob/main/src/Resizetizer/src/WindowIconGeneratorTask.cs#L48

**Comment by nickrandolph** [comment]
@ADD-David-Antolin is there something I need to do to get rules to run on generated code (for me all generated code is ignored by default)?

**Comment by ADD-David-Antolin** [comment]
@nickrandolph You are correct, I also have that enabled. I thought that was enabled by default. In our case it is via global Directory.Build.props file. Anyway, we need that class to comply with the rule.

**Comment by nickrandolph** [comment]
The fix has been merged so if you want to update to the latest Dev build of resizetizer you can test out the fix. Let me know if it does, and we can trigger a backport and push an updated release
