### ISSUE TITLE
[WASM] When splash screen background color is changed the logo image background stays the old color

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno.resizetizer#156]
## Current behavior

After running the WASM app locally, I tried changing the background color in base.props and ran again. This changed the color of the "background" of the splash screen (e.g. the area around Uno Logo image), but the background of the Uno logo image (the square that contains it) still had blue background - it seems it does not re-render the image assets after splash background color change, in case the assets were already generated

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by pictos** [comment]
@MartinZikmund if you do a rebuild does it updates?

**Comment by MartinZikmund** [comment]
@pictos I think it does, but it would be a better experience if that was not necessary (if possible)
