### ISSUE TITLE
Self-contained publication build failure

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno.resizetizer#164]
Hi, there are still issues when compiling a Skia+WPF project as self-contained for Window 7.
**.NET version:** 7
**Uno Platform version:** 4.9.17.18
**SDK list:**
- 5.0.416 [C:\Program Files\dotnet\sdk]
- 7.0.102 [C:\Program Files\dotnet\sdk]
- 7.0.109 [C:\Program Files\dotnet\sdk]
- 7.0.306 [C:\Program Files\dotnet\sdk]
- 7.0.400-preview.23274.1 [C:\Program Files\dotnet\sdk]
- 8.0.100-preview.2.23165.25 [C:\Program Files\dotnet\sdk]

This problem occurs with a fresh project created with the wizard.
In my case I get this error:

`The type or namespace name 'Resizetizer' does not exist in the namespace 'Uno' (are you missing an assembly reference?)`

A reference to Uno.Resizetizer package is already added:
![image](https://github.com/unoplatform/uno/assets/48371435/8d14dc49-e153-4793-a11a-8920497d8c20)

Maybe we should wait for a fix in a next version?

Thanks for your help.

_Originally posted by @lemalcs in https://github.com/unoplatform/uno/discussions/9970#discussioncomment-6632891_

**Comment by nickrandolph** [comment]
I think that this update should fix this issue too: https://github.com/unoplatform/uno.resizetizer/pull/166
