### ISSUE TITLE
Add image as splash background

### ISSUE THREAD

**Issue by mcocaroUX** [unoplatform/uno.resizetizer#192]
## What would you like to be added:

Ability to add an image as splash background

## Why is this needed:

We often use images as background

## For which Platform:

- [X] iOS
- [X] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

**Comment by pictos** [comment]
@mcocaroUX, by image, do you mean a `png` file?

**Comment by mcocaroUX** [comment]
@pictos yes, a png would be ok

**Comment by pictos** [comment]
@mcocaroUX I'll double check during the week, but I believe you can use a `png` file... The bad part is that `png` and `jpeg` aren't resizable by default, so it can be pixelated when resizing. Any reasons to not use a svg file?

**Comment by mcocaroUX** [comment]
What we want to do is a splash with a picture as background and the logo of the app centered (No issues showing the logo) but I don't see any option to set up the background other than the color

**Comment by pictos** [comment]
Ooh, I see now! Do you mind creating a small sample, in the way you do it today? I would like to use it as reference to do some research around that

**Comment by nickrandolph** [comment]
This isn't supported on Android (post Android 12 I think) or Windows that just put image in centre of screen with solid background color. 
As @pictos suggested, if you have a sample app you can share, we can take a look at how to support that with resizetizer

**Comment by mcocaroUX** [comment]
@pictos @nickrandolph I'm not sure what should I include on a sample app for this, given that Im not getting any error. I can create a new project with the image I want to add, does that would help?

**Comment by pictos** [comment]
@mcocaroUX yes, that does help... The idea of the sample is just show us how you do it today, and how we can automate it (if possible)

**Comment by mcocaroUX** [comment]
Ok, I created the sample.
Just to clarify, this is what we archived:
![image](https://github.com/unoplatform/uno.resizetizer/assets/94198647/b4295035-516e-4e8d-9d13-6e9cd57f1f11)

And this is what we want to archive:
![image](https://github.com/unoplatform/uno.resizetizer/assets/94198647/b399f69f-814a-41e2-beb0-164c2b8ab6c9)

Sample:
[SplashSample.zip](https://github.com/unoplatform/uno.resizetizer/files/13340587/SplashSample.zip)

**Comment by francoistanguay** [comment]
As Adnroid 12 doesnt support it, we're nt planning to support/fix this at this point in time.
