### ISSUE TITLE
[Android] Splash screen seems blurry

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno.resizetizer#224]
After generating a Splash Screen with Resizetizer, it seems the result is blurry.

I think the cause might be this line:

https://github.com/unoplatform/uno.resizetizer/blob/4930260305aa93e927a35c14b3891a5caa80e07a/src/Resizetizer/src/GenerateSplashAndroidResources.cs#L42C3-L42C41

Even though resizetizer generates scaled PNGs, they are then "resized" to match this `108` value, which does not seem correct, as the `.png` files themselves have a different sizing

**Comment by agneszitte** [comment]
@MartinZikmund still happening lately?

**Comment by MartinZikmund** [comment]
[Sample.zip](https://github.com/unoplatform/uno.resizetizer/files/15199971/Sample.zip)

Here is the files I was using, but I tried other SVGs, and it seems the result is always blurry, whatever values I choose

**Comment by MartinZikmund** [comment]
#258 could help here

**Comment by dansiegel** [comment]
After further review there isn't much to be done here. This seems to be working as expected. I'm closing this as being replaced by Issue #258 that @MartinZikmund referenced.
