### ISSUE TITLE
[wasm] splashscreen assets do not always get included in the output (VS only)

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno.resizetizer#243]
In some unknown conditions, maybe incremental builds, splash screen assets may not be included properly in the dist output. Visual Studio only.

**Comment by pedrojesus-work** [comment]
@jeromelaban did you try with the latest stable or the dev version?

**Comment by jeromelaban** [comment]
@mergifyio backport release/stable/1.4

**Comment by jeromelaban** [comment]
[UnoApp144_Debug_AnyCPU_Build_2024-04-18T17_22_15.0080842-04_00.binlog.zip](https://github.com/unoplatform/uno.resizetizer/files/15030754/UnoApp144_Debug_AnyCPU_Build_2024-04-18T17_22_15.0080842-04_00.binlog.zip)

**Comment by jeromelaban** [comment]
Fixed in latest dev. My testing was incorrect because temporary stamp files were still present.
