### ISSUE TITLE
Splash android incremental builds are failing

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno.resizetizer#254]
## Current behavior

From https://github.com/unoplatform/uno/discussions/16417:

```
1>C:\Test\Uno52\Uno52\obj\Debug\net8.0-android\unoresizetizer\sp\drawable\uno_splash_image.xml(2): error APT2260: resource drawable/splash_screen (aka com.companyname.Uno52:drawable/splash_screen) not found.
1>C:\Test\Uno52\Uno52\obj\Debug\net8.0-android\unoresizetizer\sp\drawable\uno_splash_image.xml(2): error APT2260:
1>C:\Test\Uno52\Uno52\obj\Debug\net8.0-android\unoresizetizer\sp\drawable-v31\uno_splash_image.xml(2): error APT2260: resource drawable/splash_screen (aka com.companyname.Uno52:drawable/splash_screen) not found.
1>C:\Test\Uno52\Uno52\obj\Debug\net8.0-android\unoresizetizer\sp\drawable-v31\uno_splash_image.xml(2): error APT2260:
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.95\tools\Xamarin.Android.Aapt2.targets(156,3): error APT2061: failed linking file resources.
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.95\tools\Xamarin.Android.Aapt2.targets(156,3): error APT2061:
```
## Expected behavior

No failures.

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by eriklimakc** [comment]
I had this error and got a binlog. After that I cleaned and it launched without any errors.

Binlog -> [gallery-single-project-android.zip](https://github.com/unoplatform/uno.resizetizer/files/15161859/gallery-single-project-android.zip)

cc @jeromelaban @pedrojesus-work @vatsashah45

**Comment by dansiegel** [comment]
@eriklimakc we need all of the logs for all builds and design time builds from when you opened the project until you hit the error. We cannot reproduce this without that.
