### ISSUE TITLE
[Docs] Single project usage

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno.resizetizer#260]
## What would you like clarification on:

Resizetizer usage in context of Single project apps

**Comment by agneszitte** [comment]
@MartinZikmund if you can add more info for this issue based on what you shared this morning and based on the current documentation please. That would help anyone who will be working on this issue.

**Comment by agneszitte** [comment]
Related doc issue: https://github.com/unoplatform/uno.resizetizer/issues/261

**Comment by kazo0** [comment]
We should be adding a new tab for the single project structure and make it the default in multiple places like here:
<img width="818" alt="image" src="https://github.com/unoplatform/uno.resizetizer/assets/4793020/1bdf6b34-4bc6-4073-8f15-cae402673de1">

**Comment by kazo0** [comment]
We should also be mentioning the fact that we are exposing new properties that you can use to customize the <UnoSplashScreen> and <UnoIcon> items since they are now hidden behind the magic curtain:

https://github.com/unoplatform/uno/blob/6baa062e1a072c29b4827e27f3b5751f9f4aa52b/src/Uno.Sdk/targets/Uno.DefaultItems.Resizetizer.targets#L4-L12

**Comment by kazo0** [comment]
<img width="931" alt="image" src="https://github.com/unoplatform/uno.resizetizer/assets/4793020/97ae429a-0bf8-4365-9796-534928878de1">


We should also be updating the link to a proper single project sample app that is overriding all of these properties. Currently the link points to here: https://github.com/unoplatform/uno.resizetizer/tree/main/samples/NewTemplate

Which looks to be some sort of template and not an actual sample app?

**Comment by agneszitte** [comment]
> As discussed. This isn't a change we really want to make to the templates because the starting point should be by design as simplistic as possible. To address the issues of knowing how to configure the Icon / SplashScreen we already have some intellisense support with the Uno.Sdk and are looking at ways we can expand this.

Additionally we need to do a review of the docs for the Uno.Sdk and Uno.Resizetizer to ensure that there is proper back linking between relevant docs and ensure that it remains easy for people to see how they can either customize these items with the properties provided by the Uno.Sdk or take manual control with the available metadata for each item that is used by Resizetizer.

_Originally posted by @dansiegel in https://github.com/unoplatform/uno.templates/issues/662#issuecomment-2088422902_
