### ISSUE TITLE
Changing `.svg` file build action to `Content` causes error

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno.resizetizer#264]
## Current behavior

When you add a `.svg` file to Uno project and try to change its action via Properties window from `UnoIcon` to `Content`, Visual Studio shows the following nondescript error:

![image](https://github.com/unoplatform/uno.resizetizer/assets/1075116/82b507fb-a00d-4edd-8f60-47e90ed7810c)

## Expected behavior

No error.

## How to reproduce it (as minimally and precisely as possible)

1. Create a blank uno app
2. Add a `.svg` to the root of `Assets` folder
3. Try to change its Build action to `Content`

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by agneszitte** [comment]
@MartinZikmund closing this issue as we already have https://github.com/unoplatform/uno/issues/15863#issuecomment-1992592751
Seems like a VS related issue, so normally not related to Resizetizer directly
(cc @jeromelaban)
