### ISSUE TITLE
[WinAppSDK Packaged] Taskbar icon and app icon are not set

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno.resizetizer#269]
## Current behavior

When I replaced the `icon_foreground.svg` file and `splash_screen.svg` file with custom `svg`, see repro; and ran the app, the title bar icon was set correctly, but the app's start menu icon remained Uno logo and task bar icon is invisible:

![image](https://github.com/unoplatform/uno.resizetizer/assets/1075116/6bbdb044-edb5-4795-9de3-14cd1e4a3e37)

## Expected behavior

Should work out of the box.

## How to reproduce it (as minimally and precisely as possible)

1. Create a blank Uno app or default preset Uno app
2. Replace the `icon_foreground.svg` and `splash_screen.svg` with [this file](https://github.com/unoplatform/uno.resizetizer/assets/1075116/d3c640b6-53a4-4ef9-8ced-0a2982d6c59d)
3. Clean bin/obj just to make sure changes are applied
4. Rebuild to make sure changes are applied
5. Run the Windows App SDK target **(Packaged)**
6. **Notice taskbar icon is invisible and app icon in start menu is just plain Uno Platform logo**

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [x] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Could it be that the app should be reinstalled to have this work? Feels like a winappsdk issue.

**Comment by dansiegel** [comment]
@MartinZikmund have you looked in the obj to see what the files were that got generated? Were they generated as expected or was there an issue with what Resizetizer generated there?

**Comment by MartinZikmund** [comment]
@jeromelaban I tried uninstall, but that didn't help

@dansiegel will try and let you know 👍

**Comment by MartinZikmund** [comment]
@dansiegel @jeromelaban indeed when I now tried on a different device the icon appears correctly. This seems like Windows cached the icons somehow and kept it even though I uninstalled the app completely in between. I will add docs on how to reset icon cache, as that might help in such situation
